[build]
  command = "npm run build"
  publish = "build"

# Redirigir todas las rutas a index.html para que funcione el enrutamiento del lado del cliente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build" 